Workaround: tweak the OZ Upgrades file to adapt to new incompatible layout
A previous commit in the TokenStaking contract (https://github.com/threshold-network/solidity-contracts/pull/87/commits/6eaf4d59c25f9d92687e68667e992a01f975ea79) introduced a potential change in the contract storage layout that is detected by the OZ Upgrades tool:

Error: New storage layout is incompatible

contracts/staking/TokenStaking.sol:130: Upgraded `slashingQueue` to an incompatible type
  - In struct TokenStaking.SlashingEvent[]
    - Bad upgrade to struct TokenStaking.SlashingEvent
  - In struct TokenStaking.SlashingEvent
    - Deleted `application`
      > Keep the variable even if unused

The good news is that this struct is still unused since there are no real applications running yet, so there's no consequences. As a workaround, we decided to tweak the OZ Upgrades layout file to adapt to the new layout. Going forward we will implement automatic checks that verify the layout of any potential change to the staking contract.